<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: interactivefb.proto

namespace GPBMetadata;

class Interactivefb
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0ab5010a13696e74657261637469766566622e70726f746f2295010a0e696e7465726163746976655f6662120f0a07706c61745f696418012001280912100a086d656469615f696418022001280912120a0a61645f736c6f745f696418032001280912130a0b74656d706c6174655f6964180420012809120f0a07706c616e5f696418052001280912100a0861776172645f696418062001280912140a0c6164766572746973655f6964180720012809620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

