<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: interactivefb.proto

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>interactive_fb</code>
 */
class interactive_fb extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string plat_id = 1;</code>
     */
    protected $plat_id = '';
    /**
     * Generated from protobuf field <code>string media_id = 2;</code>
     */
    protected $media_id = '';
    /**
     * Generated from protobuf field <code>string ad_slot_id = 3;</code>
     */
    protected $ad_slot_id = '';
    /**
     * Generated from protobuf field <code>string template_id = 4;</code>
     */
    protected $template_id = '';
    /**
     * Generated from protobuf field <code>string plan_id = 5;</code>
     */
    protected $plan_id = '';
    /**
     * Generated from protobuf field <code>string award_id = 6;</code>
     */
    protected $award_id = '';
    /**
     * Generated from protobuf field <code>string advertise_id = 7;</code>
     */
    protected $advertise_id = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $plat_id
     *     @type string $media_id
     *     @type string $ad_slot_id
     *     @type string $template_id
     *     @type string $plan_id
     *     @type string $award_id
     *     @type string $advertise_id
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Interactivefb::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string plat_id = 1;</code>
     * @return string
     */
    public function getPlatId()
    {
        return $this->plat_id;
    }

    /**
     * Generated from protobuf field <code>string plat_id = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setPlatId($var)
    {
        GPBUtil::checkString($var, True);
        $this->plat_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string media_id = 2;</code>
     * @return string
     */
    public function getMediaId()
    {
        return $this->media_id;
    }

    /**
     * Generated from protobuf field <code>string media_id = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setMediaId($var)
    {
        GPBUtil::checkString($var, True);
        $this->media_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string ad_slot_id = 3;</code>
     * @return string
     */
    public function getAdSlotId()
    {
        return $this->ad_slot_id;
    }

    /**
     * Generated from protobuf field <code>string ad_slot_id = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setAdSlotId($var)
    {
        GPBUtil::checkString($var, True);
        $this->ad_slot_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string template_id = 4;</code>
     * @return string
     */
    public function getTemplateId()
    {
        return $this->template_id;
    }

    /**
     * Generated from protobuf field <code>string template_id = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setTemplateId($var)
    {
        GPBUtil::checkString($var, True);
        $this->template_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string plan_id = 5;</code>
     * @return string
     */
    public function getPlanId()
    {
        return $this->plan_id;
    }

    /**
     * Generated from protobuf field <code>string plan_id = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setPlanId($var)
    {
        GPBUtil::checkString($var, True);
        $this->plan_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string award_id = 6;</code>
     * @return string
     */
    public function getAwardId()
    {
        return $this->award_id;
    }

    /**
     * Generated from protobuf field <code>string award_id = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setAwardId($var)
    {
        GPBUtil::checkString($var, True);
        $this->award_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string advertise_id = 7;</code>
     * @return string
     */
    public function getAdvertiseId()
    {
        return $this->advertise_id;
    }

    /**
     * Generated from protobuf field <code>string advertise_id = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setAdvertiseId($var)
    {
        GPBUtil::checkString($var, True);
        $this->advertise_id = $var;

        return $this;
    }

}

